[workspace]
resolver = "2"
members = ["crates/kubizone-common"]

[workspace.dependencies]
schemars = "0.9.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_yaml = { package = "serde_yaml_ng", version = "0.10.0" }
